# Thông tin nhận chuyển khoản của cửa hàng (dùng để tạo QR / nội dung thanh toán)
# Bạn có thể để trống nếu không dùng chuyển khoản.

pay.bankName=Vietcombank
pay.accountNo=9367678723
pay.accountName=NGUYEN MINH TRUONG
